spring:
  application:
    name: account-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  batch:
    jdbc:
      initialize-schema: always
      platform: mysql

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 1000
        order_updates: true
        order_inserts: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 1234
    #    username: "${DB_USERNAME}"
    #    password: "${DB_PASSWORD}"
    #    url: jdbc:mysql://mysql-service:3306/test_db
    url: jdbc:mysql://mysql-service:3306/test_db?rewriteBatchedStatements=true

  data:
    redis:
      host: redis-service
      port: 6379
      #      password: 1234
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      password: 1234
  #      password: "${REDIS_PASSWORD}"
  kafka:
    bootstrap-servers:
      - kafka-mq:9090

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all

      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        retries: 1
        max.in.flight.requests.per.connection: 5
        allow.auto.create.topics: false

      batch-size: 32768 #32kb
      buffer-memory: 67108864 # 64mb

    admin:
      auto-create: false # AdminClient 비활성화 (Kafka 토픽 자동 생성 안 쓰면 가능)

custom:
  config:
    topic-partitions: 1
    topic-replications: 1

  cart:
    topic:
      command: cart-command

  image:
    allowed-extension: jpg,jpeg,png,webp
    max-size: 10485760 # 10mb
    default: https://team03-ctrlz-5775efc3-b7e8.s3.ap-northeast-2.amazonaws.com/images/USER/defualt-profile-image.png


  redirectUrl: https://api.yeongeun.chlab.org

# k8s 설정
eureka:
  instance:
    prefer-ip-address: true
    hostname: account-service
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    enabled: true