spring:
  application:
    name: account-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  batch:
    jdbc:
      initialize-schema: always
      platform: mysql

    job:
      enabled: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 1000
        order_updates: true
        order_inserts: true
    defer-datasource-initialization: true # Hibernate 초기화 후 data.sql 실행

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/domain_dev?rewriteBatchedStatements=true
    username: app
    password: 1234

  # datasource:
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password:
  #   url: jdbc:h2:mem:user-db
  # #
  # h2:
  #   console:
  #     enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  kafka:
    bootstrap-servers:
      - localhost:9090

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all

      properties:
        delivery.timeout.ms: 120000
        linger.ms: 300
        request.timeout.ms: 30000
        enable.idempotence: true
        retries: 1
        max.in.flight.requests.per.connection: 5
        allow.auto.create.topics: false

      batch-size: 65536 #64kb
      buffer-memory: 67108864 # 64mb

    listener:
      auto-startup: false

    admin:
      auto-create: false # AdminClient 비활성화 (Kafka 토픽 자동 생성 안 쓰면 가능)

custom:
  config:
    topic-partitions: 1
    topic-replications: 1

  cart:
    topic:
      command: cart-command

  deposit:
    topic:
      command: deposit-command

  image:
    allowed-extension: jpg,jpeg,png,webp
    max-size: 10485760 # 10mb
    default: https://team03-ctrlz-5775efc3-b7e8.s3.ap-northeast-2.amazonaws.com/images/USER/defualt-profile-image.png

  redirectUrl: http://localhost:8000

logging:
  config: classpath:logback-local.xml
  level:
    io.awspring.cloud: DEBUG
    org.springframework.batch: DEBUG

# k8s 설정
eureka:
  #  instance:
  #    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

# Management 설정
management:
  health:
    redis:
      enabled: false
