apiVersion: v1
kind: ConfigMap
metadata:
  name: elk-config-map

data:
  # Elasticsearch 설정
  ES_NODE_NAME: "es01"
  ES_CLUSTER_NAME: "cluster-exp"

  # Logstash 설정
  MYSQL_DATABASE: "app_db"
  MYSQL_USER: "app"
  MYSQL_PASSWORD: "app123"
  
  # Kibana 설정
  ELASTICSEARCH_HOSTS: "http://elasticsearch-svc:9200"
