apiVersion: v1

kind: ConfigMap

metadata:
  name: zipkin-config-map
#임시
data:
  STORAGE_TYPE: "mysql"
  MYSQL_HOST: "mysql-svc"
  MYSQL_TCP_PORT: "3306"
  MYSQL_USER: "admin"
  MYSQL_PASS: "1234"
  MYSQL_DB: "zipkin"



