services:

  redis:
    image: redis:latest
    container_name: redis_local
    ports:
      - "6379:6379"
    restart: unless-stopped

  db-mysql:
    image: mysql
    container_name: db-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - TZ=Asia/Seoul

  elasticsearch:
    image: eddie1031/es:9.1.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - cluster.name=cluster-exp
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  logstash:
    image: eddie1031/ls:9.1.3
    container_name: logstash
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "5044:5044"
    volumes:
       - ./lib/pipeline:/usr/share/logstash/pipeline

  kibana:
    image: kibana:9.1.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
