apiVersion: v1

kind: ConfigMap

metadata:
  name: mysql-config-map

data:
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "1234"
  MYSQL_DATABASE: "test_db"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  TZ: "Asia/Seoul"



