apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-deploy
  labels:
    app: batch

spec:
  schedule: "30 1 * * *"
  # 성공한 작업 기록 유지 개수
  successfulJobsHistoryLimit: 3
  # 실패한 작업 기록 유지 개수
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: batch
        spec:
          restartPolicy: OnFailure
          containers:
            - name: batch-service-app
              image: docker.io/beatchoi156/batch-service-app:latest
              env:
                - name: LOG_PATH
                  value: "/app/logs"

              envFrom:
                - secretRef:
                    name: spring-prod-secret

              ports:
                - containerPort: 8085
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
            - name: domain-logs
              mountPath: /domain-logs
      volumes:
        - name: log-volume
          hostPath:
            path: /var/log/spring-apps/batch-service
            type: DirectoryOrCreate
        - name: domain-logs
          hostPath:
            path: /var/log/spring-apps/domain-service
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service

metadata:
  name: batch-svc
spec:
  selector:
    app: batch

  sessionAffinity: None
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8085
