server:
  port: 8082

spring:
  application:
    name: gateway-service

  data:
    redis:
      port: 6379
      host: localhost

  cloud:
    gateway:
      observations:
        http:
          server:
            enabled: true
          client:
            enabled: true
      server:
        webflux:
          routes:
            - id: oauth-login
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/oauth2/authorization/google
                - Method=GET

            - id: oauth-callback
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/login/oauth2/code/google
                - Method=GET
              filters:
                - name: PreserveHostHeader
                - name: AccessTokenCaptureFilter
                - name: IpCaptureFilter

            - id: post-search-public
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/product-posts/**
                - Method=GET
              filters:
                - name: ProductSearchFilter

            - id: user-sign-up
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/users
                - Method=POST

              filters:
                - name: AccessTokenCaptureFilter
                - name: IpCaptureFilter

            - id: user-api-protected
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/users/**
                - Method=GET,PATCH,DELETE
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: USER

            - id: auth-api-protected
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/auth/refresh
                - Method=GET
              filters:
                - name: AccessTokenCaptureFilter
                - name: IpCaptureFilter
                - name: ReissueTokenFilter

            - id: post-api-protected
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/product-posts/**
                - Method=POST,PUT,DELETE,PATCH
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: SELLER

            - id: cart-api-protected
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/carts/**
                - Method=GET,PATCH,DELETE,POST
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: USER

            - id: deposit-api-protected
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/deposits/**
                - Method=GET,POST
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: USER

            - id: order-api-protected
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/orders/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: USER

            - id: payment-api-open
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/payments/**
                - Method=GET,POST,PATCH,DELETE

 # k8s 설정
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: gateway-service

