spring:
  logging:
    config: classpath:logback-local.xml

  data:
    redis:
      host: localhost
      # password 없음

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG

custom:
  redirect-url: http://localhost:8082
