spring:
  logging:
    config: classpath:logback-prod.xml

  data:
    redis:
      host: redis-svc
      password: ${REDIS_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
    hostname: gateway-service
  client:
    serviceUrl:
      defaultZone: http://discovery-svc:8761/eureka/

custom:
  redirect-url: https://api.yeongeun.chlab.org/