server:
  port: 8082

spring:
  application:
    name: gateway-service

  logging:
    config: classpath:logback-prod.xml

  data:
    redis:
      port: 6379
      host: redis-svc
      password: ${REDIS_PASSWORD}

  cloud:
    gateway:
      observations:
        http:
          server:
            enabled: true
          client:
            enabled: true
      server:
        webflux:
          routes:
            - id: tag-search-public
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/tags
                - Method=GET

            - id: category-search-public
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/categories
                - Method=GET

            - id: tag-search-public
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/tags
                - Method=GET

            - id: category-search-public
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/categories
                - Method=GET

            - id: user-sign-up
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/users
                - Method=POST
              filters:
                - name: AccessTokenCaptureFilter
                - name: IpCaptureFilter

            - id: user-api-protected
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/users/**
                - Method=GET,PATCH,DELETE
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: USER

            - id: auth-api-protected
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/auth/reissue
                - Method=POST  # CSRF 방어를 위해 POST 사용

              filters:
                - name: AccessTokenCaptureFilter
                - name: IpCaptureFilter
                - name: ReissueTokenFilter

            - id: post-api-protected
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/product-posts/**
                - Method=POST,PUT,DELETE,PATCH
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: SELLER

            - id: cart-api-protected
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/carts/**
                - Method=GET,PATCH,DELETE,POST
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: USER

            - id: deposit-api-protected
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/deposits/**
                - Method=GET,POST
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: USER

            - id: order-api-protected
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/orders/**
                - Method=GET,POST,PATCH,DELETE
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: USER

            - id: payment-api-open
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/payments/**
                - Method=GET,POST,PATCH,DELETE

            - id: post-search-public
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/product-posts/**
                - Method=GET
              filters:
                - name: ProductSearchFilter

            - id: search-word-public
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/searches/**
                - Method=GET,POST

            - id: search-word-redis-public
              uri: lb://DOMAIN-SERVICE
              predicates:
                - Path=/api/searches/redis-test
                - Method=GET,DELETE

            - id: ai-service-sse
              uri: lb://AI-SERVICE
              predicates:
                - Path=/sse/**
                - Method=GET
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: USER

            - id: ai-service-polling
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/recommendations/**
                - Method=GET
              filters:
                - name: AuthenticationFilter
                  args:
                    requiredRole: USER
services:
  account:
    url: lb://ACCOUNT-SERVICE

  # k8s 설정
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-svc:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: gateway-service

custom:
  # 수정 필요
  redirect-url: https://api.yeongeun.chlab.org/