spring:
  application:
    name: user-service
  profiles:
    group:
      local:
        - secret

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:user-db

  h2:
    console:
      enabled: true


  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all

      properties:
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        enable.idempotence: true
        allow.auto.create.topics: false

custom:
  config:
    topic-partitions: 1
    topic-replications: 1

  cart:
    topic:
      command: cart-command

  deposit:
    topic:
      command: deposit-command

  image:
    allowed-extension: jpg,jpeg,png,webp
    max-size: 10485760 # 10mb
    default: https://team03-ctrlz-5775efc3-b7e8.s3.ap-northeast-2.amazonaws.com/images/USER/defualt-profile-image.png

logging:
  level:
    io.awspring.cloud: DEBUG

