spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:user-db




custom:
  config:
    topic-partitions: 1
    topic-replications: 1

  cart:
    topic:
      command: cart-command


