spring:
  profiles:
    active: prod
---
server:
  port: 8761

spring:
  application:
    name: discovery-server

#  management:
#    tracing:
#      sampling:
#        probability: 1.0
#
#      propagation:
#        consume: b3
#        produce: b3_multi
#
#    zipkin:
#      tracing:
#        endpoint: http://localhost:9411/api/v2/spans
#
#    endpoints:
#      web:
#        exposure:
#          include: "*"

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

#logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

