spring:
  application:
    name: zipkin

management:
  tracing:
    sampling:
      probability: 1.0

    propagation:
      consume: b3
      produce: b3
      type: b3

    brave:
      span-joining-supported: true

  zipkin:
    sender:
      type: kafka # 이 설정은 Spring Boot 3.x+의 micrometer-tracing에서는 직접 지원하지 않을 수 있습니다.
    kafka:
      topic: zipkin
    tracing:
      endpoint: http://zipkin-svc:9411/api/v2/spans


