spring:
  application:
    name: zipkin

management:
  tracing:
    sampling:
      probability: 1.0

    propagation:
      consume: b3
      produce: b3
      type: b3

    brave:
      span-joining-supported: true

  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans


