spring:
  application:
    name: asset

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    io.awspring.cloud: DEBUG

custom:
  image:
    allowed-extension: jpg,jpeg,png,webp
    max-size: 10485760 # 10mb