server:
  port: 8085

spring:
  batch:
    job:
      enabled: false

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/domain_dev?rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true
    username: app
    password: 1234
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:settlement_dev;MODE=MySQL
#    username: sa
#    password:
#    hikari:
#      auto-commit: false

#  kafka:
#    bootstrap-servers: localhost:9090
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#    consumer:
#      group-id: settlement-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "com.common.event"
#    listener:
#      auto-startup: false

# 배치 작업 설정
batch:
  search:
    log-directory: logs
    log-pattern: item-view.log*,search-view.log*
    chunk-size: 1000
    skip-limit: 100
    pool-size: 4

logging:
  config: classpath:logback-local.xml

