server:
  port: 8085

spring:
  batch:
    job:
      enabled: false

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/domain_dev?rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true
    username: app
    password: 1234


# 배치 작업 설정
batch:
  search:
    log-directory: logs
    log-pattern: item-view.log*,search-view.log*
    chunk-size: 1000
    skip-limit: 100
    pool-size: 4

logging:
  config: classpath:logback-local.xml

custom:
  feign:
    url:
      payment-service: http://localhost:8084
