payment:
  toss:
    test_client_api_key: test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
    test_secrete_api_key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    targetUrl: https://api.tosspayments.com/v1/payments


