server:
  port: 8081

spring:
  application:
    name: domain-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  profiles:
    active: local
    group:
      local:
        - secret

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:domain_dev;MODE=MySQL
#    username: sa
#    password:
#    hikari:
#      auto-commit: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${custom.db.database}
    username: "${custom.db.username}"
    password: "${custom.db.password}"

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true  # Hibernate 초기화 후 data.sql 실행

  sql:
    init:
      mode: always  # data.sql을 항상 실행

  data:
    redis:
      port: 6379
      host: localhost

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: domain-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.common.event"
    listener:
      auto-startup: false
    admin:
      auto-create: false

  elasticsearch:
    uris: http://localhost:9200 # default 지만 명시적으로 작성

# k8s 설정
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false

custom:
  image:
    allowed-extension: jpg,jpeg,png,webp
    max-size: 10485760 # 10mb
    default: https://team03-ctrlz-5775efc3-b7e8.s3.ap-northeast-2.amazonaws.com/images/USER/defualt-profile-image.png

  config:
    topic-partitions: 1
    topic-replications: 1

  cart:
    topic:
      command: cart-command

  deposit:
    topic:
      command: deposit-command

  feign:
    url:
      user-service: localhost:8080

---
spring:
  config:
    activate:
      on-profile: kafka-on

  kafka:
    listener:
      auto-startup: true