server:
  port: 8081

spring:
  application:
    name: domain-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  profiles:
    active: local
    group:
      local:
        - secret

  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:domain_dev;MODE=MySQL
  #    username: sa
  #    password:
  #    hikari:
  #      auto-commit: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${custom.db.database}
    username: "${custom.db.username}"
    password: "${custom.db.password}"

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true # 1. resources 경로에 data.sql/schema.sql 스크립트를 실행해줌

  sql:
    init:
      mode: always # 2. SQL 스크립트를 실행할 수 있도록 변경

  data:
    redis:
      port: 6379
      host: localhost
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: domain-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.common.event"
    listener:
      auto-startup: false

  elasticsearch:
    uris: http://localhost:9200 # default 지만 명시적으로 작성

custom:
  image:
    allowed-extension: jpg,jpeg,png,webp
    max-size: 10485760 # 10mb
    default: https://team03-ctrlz-5775efc3-b7e8.s3.ap-northeast-2.amazonaws.com/images/USER/defualt-profile-image.png

---
spring:
  config:
    activate:
      on-profile: kafka-on

  kafka:
    listener:
      auto-startup: true