spring:
  logging:
    config: classpath:logback-prod.xml

  datasource:
    url: jdbc:mysql://mysql-svc:3306/test_db?rewriteBatchedStatements=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        # 운영에서는 SQL 포맷팅 제거
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 1000

  data:
    redis:
      port: 6379
      host: redis-svc
      password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: kafka-svc:9090
    consumer:
      properties:
        spring.json.trusted.packages: "com.common.event.**"

  elasticsearch:
    uris: http://elasticsearch-svc:9200

eureka:
  instance:
    hostname: domain-service
  client:
    serviceUrl:
      defaultZone: http://discovery-svc:8761/eureka/

custom:
  feign:
    url:
      user-service: http://account-svc:8080

openapi:
  service:
    url: https://api.yeongeun.chlab.org