spring:
  logging:
    config: classpath:logback-local.xml

  datasource:
    url: jdbc:mysql://localhost:3307/domain_dev?rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true
    username: app
    password: 1234

  data:
    redis:
      port: 6379
      host: localhost

  kafka:
    bootstrap-servers: localhost:9090
    consumer:
      properties:
        spring.json.trusted.packages: com.common.event.**
        delivery.timeout.ms: 120000
        linger.ms: 300
        request.timeout.ms: 30000
        enable.idempotence: true
        retries: 1
        max.in.flight.requests.per.connection: 5

  elasticsearch:
    uris: http://localhost:9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

custom:
  feign:
    url:
      user-service: localhost:8080
  port:
    gateway: 8082

openapi:
  service:
    url: http://localhost:${custom.port.gateway}

logging:
  config: classpath:logback-local.xml