name: discovery-service ci/cd

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - pushtest
    paths:
      - 'discovery-service/**'
      - 'observability-config/**'
      - '.github/workflows/discovery-cd-workflow.yml'

jobs:
  releasing:
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/release-workflow.yml
    secrets: inherit # discovery 에는 secret.yml 이 없어 따로 읽지 않음
    with:
      service-name: discovery-service-app
      service-dir: .
      secret-dir: discovery-service
      file-name: docker/discovery-service.dockerfile


#  deploying:
#    needs: releasing
#    uses: ./.github/workflows/deploy-workflow.yml
#    secrets: inherit
#    with:
#      pod-name: discovery-service-app # pod랑 같은 이름
#      deploy-name: discovery-deploy # deployment랑 같은 이름
#      label-name: discovery # pod 라벨 이름
#      image-tag: ${{ needs.releasing.outputs.tag_name }}



