name: payment-service ci/cd

on:
  workflow_dispatch:
  push: # 메인에 push 될때 수행됨.
    branches:
      - main
      - pushtest
    paths:
      - 'payment-service/**'
      - 'common/**'
      - '**/*.dockerfile'
      - '.github/workflows/payment-cd-workflow.yml'
      - 'observability-config/**'

jobs:
  releasing:
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/release-workflow.yml
    secrets:
      APPLICATION_SECRET: ${{ secrets.APPLICATION_PAYMENT_SECRET }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_AC_KEY: ${{ secrets.DOCKER_AC_KEY }}

    with:
      service-name: payment-service-app
      service-dir: .
      secret-dir: payment-service
      file-name: docker/payment-service.dockerfile

#  deploying:
#    needs: releasing
#    uses: ./.github/workflows/deploy-workflow.yml
#    secrets: inherit
#
#    with:
#      pod-name: payment-service-app # pod랑 같은 이름
#      deploy-name: payment-deploy # deployment랑 같은 이름
#      label-name: payment # pod 라벨 이름
#      image-tag: ${{ needs.releasing.outputs.tag_name }}


