name: Build and release docker image

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-dir:
        required: true
        type: string
      secret-dir:
        required: true
        type: string
      file-name:
        required: true
        type: string
    secrets:
      APPLICATION_SECRET: ## 각각의 cd-workflow 에서 넘어올 때 secret.yml 정보 가져오기
        required: false # secret이 있으면 가져오고 없으면 빈 값
        description: 'Application secret yml content'
      DOCKER_USERNAME:
        required: true
      DOCKER_AC_KEY:
        required: true
    outputs:
      tag_name:
        value: ${{ jobs.tagging.outputs.tag_name }}

env:
  REGISTRY: docker.io

jobs:
  tagging:
    name: 태깅 및 릴리즈
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag_version.outputs.new_tag }}

    steps:
      - uses: actions/checkout@v5

      - name: versioning and tagging
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ inputs.service-name }}

#      - name: releasing
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.tag_version.outputs.new_tag }}
#          name: ${{ steps.tag_version.outputs.new_tag }}
#          body: ${{ steps.tag_version.outputs.changelog }}

  build-image:
    name: 도커 이미지 빌드
    runs-on: ubuntu-latest
    needs: tagging

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out Repository
        uses: actions/checkout@v5

      # 각 서비스별 application-secret.yml 생성
      - name: Create application-secret.yml
        env:
          APP_SECRET: ${{ secrets.APPLICATION_SECRET }}
        if: ${{ env.APP_SECRET != '' }}
        run: |
          mkdir -p ${{ inputs['secret-dir'] }}/src/main/resources
          echo "${APP_SECRET}" > ${{ inputs['secret-dir'] }}/src/main/resources/application-secret.yml

      - name: Sign in github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AC_KEY }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ inputs.service-name }}
          tags: |
            type=sha
            type=raw,value=${{ needs.tagging.outputs.tag_name }}
            type=raw,value=latest

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.service-dir }}
          file: ${{ inputs.service-dir }}/${{ inputs.file-name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

